### ISSUE TITLE
Cannot POST without 'filters' data

### ISSUE THREAD

**Issue by mlleprudhomme** [diabolical-ninja/smart-property-search#22]
When a basic search is attempted only sending data associated with the 'domain' key, an internal server error is returned.

Make the 'filters' part truly optional, devil-ninja! 

<img width="642" alt="Screen Shot 2020-09-13 at 8 45 50 pm" src="https://user-images.githubusercontent.com/13388095/93016393-2d633580-f604-11ea-852a-2a9976dae5da.png">

**Comment by diabolical-ninja** [comment]
Thanks for picking this up @mlleprudhomme . It's been resolved as part of #23
There's now also a test as well under: `tests/test_handler_payloads/successes/request_no_filters.json` 

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/15998949/93780371-6b4b0400-fc6b-11ea-8e19-32705ca921eb.png">

**Comment by mlleprudhomme** [comment]
Keep up the good work, thanks for making this available to all!
